version: '3.8'

services:
  graphql-api:
    build: .
    container_name: graphql-api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    restart: unless-stopped
    
  graphql-dev:
    build: .
    container_name: graphql-dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    profiles:
      - dev
    restart: unless-stopped
