services:
  graphql-api:
    build:
      context: .
      target: production
    container_name: graphql-api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - ENABLE_SANDBOX=${ENABLE_SANDBOX}
    restart: unless-stopped

  graphql-dev:
    build:
      context: .
      target: base
    container_name: graphql-dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - ENABLE_SANDBOX=${ENABLE_SANDBOX}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    profiles:
      - dev
    restart: unless-stopped

  tests:
    build:
      context: .
      target: test
    container_name: graphql-tests
    command: npm test
    profiles:
      - test
